services:
  fast-video-messaging:
    build: .
    container_name: fast-video-messaging
    command: sh -c "ts-node setup-sqs.ts && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      SQS_QUEUE_NAME: fast-video-queue
      SQS_ENDPOINT: http://localstack:4566
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:3.2
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
    volumes:
      - ./localstack:/var/lib/localstack
